-- =====================================================
-- Tabla de Idiomas para el ERP - TODOS LOS MÓDULOS
-- Soporta: ES (español), EN (inglés), ZH (chino)
-- =====================================================

-- Crear tabla languages
CREATE TABLE IF NOT EXISTS public.languages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    es TEXT,
    en TEXT,
    zh TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE public.languages ENABLE ROW LEVEL SECURITY;

-- Política para lectura pública
DROP POLICY IF EXISTS "Allow read access" ON public.languages;
CREATE POLICY "Allow read access" ON public.languages
    FOR SELECT USING (true);

-- Política para escritura (solo authenticated)
DROP POLICY IF EXISTS "Allow admin write" ON public.languages;
CREATE POLICY "Allow admin write" ON public.languages
    FOR ALL USING (auth.role() = 'authenticated');

-- =====================================================
-- TRADUCCIONES - Limpiar tabla primero
-- =====================================================
DELETE FROM public.languages WHERE true;

-- App
INSERT INTO public.languages (key, es, en, zh) VALUES
('appName', 'ERP Sistema', 'ERP System', 'ERP系统'),
('signOut', 'Cerrar sesión', 'Sign out', '退出'),
('logout', 'Salir', 'Sign out', '退出'),
('loading', 'Cargando...', 'Loading...', '加载中...'),

-- Sidebar
('dashboard', 'Dashboard', 'Dashboard', '仪表板'),
('production', 'Producción', 'Production', '生产'),
('orders', 'Órdenes', 'Orders', '订单'),
('capture', 'Captura', 'Capture', '采集'),
('routing', 'Enrutamiento', 'Routing', '路由'),
('scrap', 'Scrap', 'Scrap', '废料'),
('wip', 'WIP', 'WIP', '在制品'),
('inventory', 'Inventario', 'Inventory', '库存'),
('partNumbers', 'Partes', 'Parts', '零件'),
('traceability', 'Trazabilidad', 'Traceability', '追溯'),
('warehouse', 'Almacén', 'Warehouse', '仓库'),
('receipts', 'Recepciones', 'Receipts', '收货'),
('wmsAlmacen', 'WMS Almacén', 'WMS Warehouse', 'WMS仓库'),
('quality', 'Calidad', 'Quality', '质量'),
('qualityControl', 'Control de Calidad', 'Quality Control', '质量控制'),
('inspections', 'Inspecciones', 'Inspections', '检验'),
('scrapControl', 'Control Scrap', 'Scrap Control', '废料控制'),
('users', 'Usuarios', 'Users', '用户'),
('userManagement', 'Gestión de Usuarios', 'User Management', '用户管理'),

-- Login
('login', 'Iniciar Sesión', 'Sign In', '登录'),
('email', 'Correo electrónico', 'Email', '邮箱'),
('password', 'Contraseña', 'Password', '密码'),
('signInButton', 'Iniciar Sesión', 'Sign In', '登录'),
('forgotPassword', '¿Olvidaste tu contraseña?', 'Forgot password?', '忘记密码？'),
('noAccount', '¿No tienes cuenta?', "Don't have an account?", '没有账户？'),
('createAccount', 'Crear cuenta', 'Create account', '创建账户'),
('invalidCredentials', 'Credenciales inválidas', 'Invalid credentials', '无效凭证'),
('fillFields', 'Complete todos los campos', 'Fill in all fields', '请填写所有字段'),

-- Dashboard
('welcome', 'Bienvenido', 'Welcome', '欢迎'),
('overview', 'Resumen', 'Overview', '概览'),
('todayProduction', 'Producción de Hoy', "Today's Production", '今日生产'),
('activeOrders', 'Órdenes Activas', 'Active Orders', '活跃订单'),
('completedOrders', 'Órdenes Completadas', 'Completed Orders', '已完成订单'),
('totalWip', 'WIP Total', 'Total WIP', '总在制品'),
('inProcess', 'En Proceso', 'In Process', '处理中'),
('pending', 'Pendiente', 'Pending', '待处理'),
('completed', 'Completadas', 'Completed', '已完成'),
('onHold', 'En Espera', 'On Hold', '暂停'),
('cancelled', 'Canceladas', 'Cancelled', '已取消'),
('notStarted', 'No Iniciadas', 'Not Started', '未开始'),
('productionEfficiency', 'Eficiencia de Producción', 'Production Efficiency', '生产效率'),
('qualityRate', 'Tasa de Calidad', 'Quality Rate', '质量率'),
('scrapRate', 'Tasa de Scrap', 'Scrap Rate', '废料率'),
('inventoryValue', 'Valor de Inventario', 'Inventory Value', '库存价值'),
('units', 'unidades', 'units', '单位'),
('recentActivity', 'Actividad Reciente', 'Recent Activity', '最近活动'),
('quickActions', 'Acciones Rápidas', 'Quick Actions', '快捷操作'),
('newOrder', 'Nueva Orden', 'New Order', '新订单'),
('viewReports', 'Ver Reportes', 'View Reports', '查看报告'),

-- Orders
('orderNumber', 'Orden', 'Order', '订单'),
('productionOrders', 'Órdenes de Producción', 'Production Orders', '生产订单'),
('newProductionOrder', 'Nueva Orden de Producción', 'New Production Order', '新建生产订单'),
('editOrder', 'Editar Orden', 'Edit Order', '编辑订单'),
('orderDetails', 'Detalles de Orden', 'Order Details', '订单详情'),
('partNumber', 'Núm. Parte', 'Part #', '件号'),
('quantity', 'Cantidad', 'Quantity', '数量'),
('status', 'Estado', 'Status', '状态'),
('priority', 'Prioridad', 'Priority', '优先级'),
('dueDate', 'Fecha Entrega', 'Due Date', '交付日期'),
('startDate', 'Fecha Inicio', 'Start Date', '开始日期'),
('customer', 'Cliente', 'Customer', '客户'),
('notes', 'Notas', 'Notes', '备注'),
('actions', 'Acciones', 'Actions', '操作'),
('search', 'Buscar', 'Search', '搜索'),
('filter', 'Filtrar', 'Filter', '筛选'),
('all', 'Todos', 'All', '全部'),
('export', 'Exportar', 'Export', '导出'),
('print', 'Imprimir', 'Print', '打印'),
('view', 'Ver', 'View', '查看'),
('edit', 'Editar', 'Edit', '编辑'),
('delete', 'Eliminar', 'Delete', '删除'),
('save', 'Guardar', 'Save', '保存'),
('cancel', 'Cancelar', 'Cancel', '取消'),
('close', 'Cerrar', 'Close', '关闭'),
('confirm', 'Confirmar', 'Confirm', '确认'),
('add', 'Agregar', 'Add', '添加'),
('remove', 'Quitar', 'Remove', '移除'),
('clear', 'Limpiar', 'Clear', '清除'),
('noData', 'Sin datos', 'No data', '无数据'),
('error', 'Error', 'Error', '错误'),
('success', 'Éxito', 'Success', '成功'),
('warning', 'Advertencia', 'Warning', '警告'),
('info', 'Información', 'Info', '信息'),
('total', 'Total', 'Total', '合计'),
('subtotal', 'Subtotal', 'Subtotal', '小计'),
('quantityRequired', 'Cantidad es requerida', 'Quantity is required', '数量必填'),
('partRequired', 'Parte es requerida', 'Part is required', '零件必填'),
('orderSaved', 'Orden guardada', 'Order saved', '订单已保存'),
('orderDeleted', 'Orden eliminada', 'Order deleted', '订单已删除'),
('orderCreated', 'Orden creada', 'Order created', '订单已创建'),

-- Capture
('productionCapture', 'Captura de Producción', 'Production Capture', '生产采集'),
('newCapture', 'Nueva Captura', 'New Capture', '新建采集'),
('operation', 'Operación', 'Operation', '工序'),
('operator', 'Operador', 'Operator', '操作员'),
('machine', 'Máquina', 'Machine', '机器'),
('shift', 'Turno', 'Shift', '班次'),
('goodParts', 'Piezas Buenas', 'Good Parts', '合格品'),
('rejectedParts', 'Piezas Rechazadas', 'Rejected Parts', '废品'),
('totalParts', 'Total Piezas', 'Total Parts', '总数'),
('cycleTime', 'Tiempo Ciclo', 'Cycle Time', '周期时间'),
('efficiency', 'Eficiencia', 'Efficiency', '效率'),
('startTime', 'Hora Inicio', 'Start Time', '开始时间'),
('endTime', 'Hora Fin', 'End Time', '结束时间'),
('comments', 'Comentarios', 'Comments', '备注'),
('captureSaved', 'Captura guardada', 'Capture saved', '采集已保存'),

-- Routing
('productionRouting', 'Enrutamiento de Producción', 'Production Routing', '生产路由'),
('routingSteps', 'Pasos de Enrutamiento', 'Routing Steps', '路由步骤'),
('stepNumber', 'Paso', 'Step', '步骤'),
('workCenter', 'Centro de Trabajo', 'Work Center', '工作中心'),
('setupTime', 'Tiempo Setup', 'Setup Time', '准备时间'),
('runTime', 'Tiempo Ejecución', 'Run Time', '运行时间'),
('tools', 'Herramientas', 'Tools', '工具'),
('addStep', 'Agregar Paso', 'Add Step', '添加步骤'),
('removeStep', 'Quitar Paso', 'Remove Step', '删除步骤'),
('moveUp', 'Subir', 'Move Up', '上移'),
('moveDown', 'Bajar', 'Move Down', '下移'),
('routingSaved', 'Enrutamiento guardado', 'Routing saved', '路由已保存'),

-- Scrap
('scrapReport', 'Reporte de Scrap', 'Scrap Report', '废料报告'),
('scrapQuantity', 'Cantidad Scrap', 'Scrap Quantity', '废料数量'),
('defectType', 'Tipo Defecto', 'Defect Type', '缺陷类型'),
('rootCause', 'Causa Raíz', 'Root Cause', '根本原因'),
('correctiveAction', 'Acción Correctiva', 'Corrective Action', '纠正措施'),
('inspector', 'Inspector', 'Inspector', '检验员'),
('disposition', 'Disposición', 'Disposition', '处置'),
('rejected', 'Rechazado', 'Rejected', '拒收'),
('rework', 'Reproceso', 'Rework', '返工'),
('useAsIs', 'Usar Como Está', 'Use As Is', '让步接受'),
('hold', 'En Espera', 'Hold', '待处理'),
('registerScrap', 'Registrar Scrap', 'Register Scrap', '登记废料'),
('scrapRegistered', 'Scrap registrado', 'Scrap registered', '废料已登记'),

-- WIP
('wipBalance', 'Balance WIP', 'WIP Balance', '在制品余额'),
('available', 'Disponible', 'Available', '可用'),
('reserved', 'Reservado', 'Reserved', '预留'),
('transactions', 'Transacciones', 'Transactions', '交易'),
('transactionType', 'Tipo Transacción', 'Transaction Type', '交易类型'),
('received', 'Recibido', 'Received', '已接收'),
('consumed', 'Consumido', 'Consumed', '已消耗'),
('adjusted', 'Ajustado', 'Adjusted', '已调整'),
('transfer', 'Transferencia', 'Transfer', '转移'),
('balanceUpdated', 'Balance actualizado', 'Balance updated', '余额已更新'),

-- Part Numbers
('partNumbersTitle', 'Números de Parte', 'Part Numbers', '件号'),
('partDescription', 'Descripción', 'Description', '描述'),
('partFamily', 'Familia', 'Family', '系列'),
('unitCost', 'Costo Unitario', 'Unit Cost', '单位成本'),
('standardCost', 'Costo Estándar', 'Standard Cost', '标准成本'),
('isActive', 'Activo', 'Active', '活跃'),
('inactive', 'Inactivo', 'Inactive', '停用'),
('newPart', 'Nueva Parte', 'New Part', '新建零件'),
('editPart', 'Editar Parte', 'Edit Part', '编辑零件'),
('partSaved', 'Parte guardada', 'Part saved', '零件已保存'),
('partDeleted', 'Parte eliminada', 'Part deleted', '零件已删除'),

-- Inventory
('inventoryTitle', 'Inventario', 'Inventory', '库存'),
('location', 'Ubicación', 'Location', '库位'),
('bin', 'Bin', 'Bin', '货位'),
('stock', 'Stock', 'Stock', '库存'),
('minStock', 'Stock Mínimo', 'Min Stock', '最小库存'),
('maxStock', 'Stock Máximo', 'Max Stock', '最大库存'),
('reorderPoint', 'Punto Reorden', 'Reorder Point', '再订货点'),
('onHand', 'En Mano', 'On Hand', '在手'),
('allocated', 'Allocado', 'Allocated', '已分配'),
('availableStock', 'Stock Disponible', 'Available Stock', '可用库存'),
('lastCount', 'Último Conteo', 'Last Count', '最后盘点'),
('lastMovement', 'Último Movimiento', 'Last Movement', '最后移动'),
('adjustStock', 'Ajustar Stock', 'Adjust Stock', '调整库存'),
('transferStock', 'Transferir Stock', 'Transfer Stock', '转移库存'),
('receiveStock', 'Recibir Stock', 'Receive Stock', '接收库存'),
('issueStock', 'Despachar Stock', 'Issue Stock', '发出库存'),
('stockAdjusted', 'Stock ajustado', 'Stock adjusted', '库存已调整'),
('stockTransferred', 'Stock transferido', 'Stock transferred', '库存已转移'),
('lowStock', 'Stock Bajo', 'Low Stock', '库存不足'),
('outOfStock', 'Sin Stock', 'Out of Stock', '缺货'),
('overstock', 'Sobrestock', 'Overstock', '库存过剩'),

-- Traceability
('traceabilityTitle', 'Trazabilidad', 'Traceability', '追溯'),
('lotNumber', 'Lote', 'Lot', '批号'),
('serialNumber', 'Serie', 'Serial #', '序列号'),
('batchTrace', 'Trazabilidad Lote', 'Batch Trace', '批次追溯'),
('genealogy', 'Genealogía', 'Genealogy', '谱系'),
('whereUsed', '¿Dónde se Usó?', 'Where Used', '用于何处'),
('whereFrom', '¿De Dónde Vino?', 'Where From', '来自何处'),
('traceForward', 'Traza Adelante', 'Trace Forward', '正向追溯'),
('traceBackward', 'Traza Atrás', 'Trace Backward', '反向追溯'),
('traceComplete', 'Trazabilidad Completa', 'Complete Traceability', '完整追溯'),

-- Warehouse Receipts
('warehouseReceipts', 'Recepciones de Almacén', 'Warehouse Receipts', '仓库收货'),
('poNumber', 'OC Proveedor', 'PO #', '采购单号'),
('supplier', 'Proveedor', 'Supplier', '供应商'),
('receiptDate', 'Fecha Recepción', 'Receipt Date', '收货日期'),
('receivedBy', 'Recibido Por', 'Received By', '收货人'),
('expectedQty', 'Cant. Esperada', 'Expected Qty', '预期数量'),
('receivedQty', 'Cant. Recibida', 'Received Qty', '实收数量'),
('discrepancy', 'Discrepancia', 'Discrepancy', '差异'),
('inspected', 'Inspeccionado', 'Inspected', '已检验'),
('pendingInspection', 'Pendiente Inspección', 'Pending Inspection', '待检验'),
('accepted', 'Aceptado', 'Accepted', '已接受'),
('notesReceipt', 'Notas', 'Notes', '备注'),
('newReceipt', 'Nueva Recepción', 'New Receipt', '新建收货'),

-- WMS Almacen
('wmsTitle', 'WMS Almacén', 'WMS Warehouse', 'WMS仓库'),
('inventoryManagement', 'Gestión Inventario', 'Inventory Management', '库存管理'),
('entries', 'Entradas', 'Entries', '入库'),
('outputs', 'Salidas', 'Outputs', '出库'),
('rawMaterials', 'Materias Primas', 'Raw Materials', '原材料'),
('locations', 'Ubicaciones', 'Locations', '库位'),
('categories', 'Categorías', 'Categories', '类别'),
('importExcel', 'Importar Excel', 'Import Excel', '导入Excel'),
('exportData', 'Exportar', 'Export', '导出'),
('locationCode', 'Código Ubicación', 'Location Code', '库位代码'),
('locationName', 'Nombre Ubicación', 'Location Name', '库位名称'),
('aisle', 'Pasillo', 'Aisle', '通道'),
('rack', 'Estante', 'Rack', '货架'),
('level', 'Nivel', 'Level', '层'),
('position', 'Posición', 'Position', '位'),
('categoryCode', 'Código Categoría', 'Category Code', '类别代码'),
('categoryName', 'Nombre Categoría', 'Category Name', '类别名称'),
('stockIn', 'Entrada Stock', 'Stock In', '入库'),
('stockOut', 'Salida Stock', 'Stock Out', '出库'),
('transferBetween', 'Transferencia entre Ubicaciones', 'Transfer Between Locations', '库位转移'),

-- Quality
('qualityTitle', 'Control de Calidad', 'Quality Control', '质量控制'),
('qualityDashboard', 'Dashboard Calidad', 'Quality Dashboard', '质量仪表板'),
('newInspection', 'Nueva Inspección', 'New Inspection', '新检验'),
('inspectionDetail', 'Detalle Inspección', 'Inspection Detail', '检验详情'),
('piecesReviewed', 'Piezas Revisadas', 'Pieces Reviewed', '已审件数'),
('approvedPieces', 'Piezas Aprobadas', 'Approved Pieces', '合格件数'),
('rejectedPieces', 'Piezas Rechazadas', 'Rejected Pieces', '不合格件数'),
('defectsFound', 'Defectos Encontrados', 'Defects Found', '发现缺陷'),
('observations', 'Observaciones', 'Observations', '观察'),
('suggestedDecision', 'Decisión Sugerida', 'Suggested Decision', '建议决定'),
('defectRate', 'Tasa de Defectos', 'Defect Rate', '缺陷率'),
('calculateGrade', 'Calificar', 'Grade', '评定'),
('saveInspection', 'Guardar Inspección', 'Save Inspection', '保存检验'),
('totalInspections', 'Total Inspecciones', 'Total Inspections', '总检验数'),
('registro', 'registros', 'records', '条记录'),
('aprobadas', 'Aprobadas', 'Approved', '合格'),
('rechazadas', 'Rechazadas', 'Rejected', '不合格'),
('requierenAccion', 'requieren acción', 'need action', '需要处理'),
('inspectionsToday', 'Inspecciones Hoy', 'Inspections Today', '今日检验'),
('inspeccionesHoy', 'Inspecciones Hoy', 'Inspections Today', '今日检验'),
('pendingInspections', 'Pendientes', 'Pending', '待处理'),
('porRevisar', 'por revisar', 'to review', '待审核'),
('piezas', 'piezas', 'pieces', '件'),
('piezasRechazadas', 'piezas rechazadas', 'rejected pieces', '拒绝件数'),
('defectoPrincipal', 'Defecto Principal', 'Main Defect', '主要缺陷'),
('masFrecuente', 'más frecuente', 'most frequent', '最频繁'),
('qualityInspection', 'Inspección de Calidad', 'Quality Inspection', '质量检验'),
('approvalRate', 'Tasa Aprobación', 'Approval Rate', '合格率'),
('tasaAprobacion', 'Tasa de Aprobación', 'Approval Rate', '合格率'),
('rejectionRate', 'Tasa Rechazo', 'Rejection Rate', '拒收率'),
('tasaRechazo', 'Tasa de Rechazo', 'Rejection Rate', '拒收率'),
('qualityIndicators', 'Indicadores Calidad', 'Quality Indicators', '质量指标'),
('indicadoresCalidad', 'Indicadores de Calidad', 'Quality Indicators', '质量指标'),
('historical', 'histórico', 'historical', '历史'),
('incidents', 'incidentes', 'incidents', '事件'),
('records', 'Registros', 'Records', '记录'),
('allDispositions', 'Todas Disposiciones', 'All Dispositions', '所有处置'),
('qualityInspector', 'Inspector Calidad', 'Quality Inspector', '质量检验员'),

-- User Management
('userManagementTitle', 'Gestión de Usuarios', 'User Management', '用户管理'),
('userName', 'Nombre', 'Name', '姓名'),
('userEmail', 'Email', 'Email', '邮箱'),
('userRole', 'Rol', 'Role', '角色'),
('userStatus', 'Estado', 'Status', '状态'),
('active', 'Activo', 'Active', '活跃'),
('lastLogin', 'Último Login', 'Last Login', '最后登录'),
('createdAt', 'Creado', 'Created', '创建于'),
('newUser', 'Nuevo Usuario', 'New User', '新建用户'),
('editUser', 'Editar Usuario', 'Edit User', '编辑用户'),
('resetPassword', 'Resetear Contraseña', 'Reset Password', '重置密码'),
('userSaved', 'Usuario guardado', 'User saved', '用户已保存'),
('userDeleted', 'Usuario eliminado', 'User deleted', '用户已删除'),
('passwordChanged', 'Contraseña cambiada', 'Password changed', '密码已更改'),
('admin', 'Administrador', 'Administrator', '管理员'),
('supervisor', 'Supervisor', 'Supervisor', '主管'),
('operator', 'Operador', 'Operator', '操作员'),
('userWarehouse', 'Almacén', 'Warehouse', '仓库'),
('userQuality', 'Calidad', 'Quality', '质量'),

-- Common
('yes', 'Sí', 'Yes', '是'),
('no', 'No', 'No', '否'),
('or', 'o', 'or', '或'),
('and', 'y', 'and', '和'),
('with', 'con', 'with', '与'),
('from', 'de', 'from', '从'),
('to', 'a', 'to', '到'),
('in', 'en', 'in', '在'),
('of', 'de', 'of', '的'),
('the', 'el/la', 'the', ''),
('by', 'por', 'by', '由'),
('date', 'Fecha', 'Date', '日期'),
('time', 'Hora', 'Time', '时间'),
('datetime', 'Fecha/Hora', 'Date/Time', '日期/时间'),
('description', 'Descripción', 'Description', '描述'),
('code', 'Código', 'Code', '代码'),
('name', 'Nombre', 'Name', '名称'),
('value', 'Valor', 'Value', '值'),
('amount', 'Monto', 'Amount', '金额'),
('percentage', 'Porcentaje', 'Percentage', '百分比'),
('required', 'Requerido', 'Required', '必填'),
('optional', 'Opcional', 'Optional', '可选'),
('selectOption', 'Seleccionar...', 'Select...', '请选择...'),
('noResults', 'Sin resultados', 'No results', '无结果'),
('refresh', 'Actualizar', 'Refresh', '刷新'),
('back', 'Volver', 'Back', '返回'),
('next', 'Siguiente', 'Next', '下一步'),
('previous', 'Anterior', 'Previous', '上一步'),
('first', 'Primero', 'First', '第一'),
('last', 'Último', 'Last', '最后'),
('page', 'Página', 'Page', '页'),
('perPage', 'por página', 'per page', '每页'),
('rowsPerPage', 'Filas por página', 'Rows per page', '每页行数'),
('showEntries', 'Mostrar entradas', 'Show entries', '显示条目'),
('showing', 'Mostrando', 'Showing', '显示'),
('entries', 'entradas', 'entries', '条')
ON CONFLICT (key) DO UPDATE SET
    es = EXCLUDED.es,
    en = EXCLUDED.en,
    zh = EXCLUDED.zh,
    updated_at = NOW();

-- Verificar conteo
SELECT 'Total traducciones:' as info, count(*) as count FROM public.languages;
